ci:
  skip: [fish_indent, fish_syntax]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/hugoh/pre-commit-fish
    rev: v1.2
    hooks:
      - id: fish_syntax
      - id: fish_indent
