tap "derailed/k9s"
tap "fishtown-analytics/dbt"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "coreutils"
brew "openssl@1.1"
brew "readline"
brew "asdf"
brew "sqlite"
brew "autojump"
brew "awscli"
brew "bat"
brew "bzip2"
brew "cmake"
brew "curl"
brew "exa"
brew "extract_url"
brew "fd"
brew "fish"
brew "fontforge"
brew "fzf"
brew "gawk"
brew "geos"
brew "libpq"
brew "gdal"
brew "gh"
brew "unbound"
brew "gnupg"
brew "libheif"
brew "imagemagick"
brew "jq"
brew "kubernetes-cli"
brew "kubectx"
brew "libiconv"
brew "libzip"
brew "luajit", args: ["HEAD"]
brew "luarocks"
brew "luv"
brew "neovim", args: ["HEAD"]
brew "ninja"
brew "postgresql"
brew "ripgrep"
brew "rustup-init"
brew "sops"
brew "the_silver_searcher"
brew "tmux"
brew "urlview"
brew "watchman"
brew "wget"
brew "yq"
brew "zlib"
brew "derailed/k9s/k9s"
cask "alacritty", args: { appdir: "/Applications" }
cask "docker", args: { appdir: "/Applications" }
cask "iterm2", args: { appdir: "/Applications" }
cask "kitty", args: { appdir: "/Applications" }
cask "postico", args: { appdir: "/Applications" }
cask "postman", args: { appdir: "/Applications" }
cask "spotify", args: { appdir: "/Applications" }
cask "visual-studio-code", args: { appdir: "/Applications" }
